/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/editor': RouteRecordInfo<'/editor', '/editor', Record<never, never>, Record<never, never>>,
    '/multiview': RouteRecordInfo<'/multiview', '/multiview', Record<never, never>, Record<never, never>>,
    '/notifications': RouteRecordInfo<'/notifications', '/notifications', Record<never, never>, Record<never, never>>,
    '/rules': RouteRecordInfo<'/rules', '/rules', Record<never, never>, Record<never, never>>,
    '/sink': RouteRecordInfo<'/sink', '/sink', Record<never, never>, Record<never, never>>,
    '/validate': RouteRecordInfo<'/validate', '/validate', Record<never, never>, Record<never, never>>,
  }
}
